-- ============================================================================
-- BRONZE LAYER — Raw Ingestion Schema
-- ============================================================================
-- All columns are VARCHAR. The _LOADED_AT column records ingestion time.
-- No foreign-key constraints. Data is stored exactly as it arrived from CSV.
-- ============================================================================

USE DATABASE RCM_ANALYTICS;
USE SCHEMA BRONZE;

CREATE TABLE IF NOT EXISTS PAYERS (
    PAYER_ID              VARCHAR,
    PAYER_NAME            VARCHAR,
    PAYER_TYPE            VARCHAR,
    AVG_REIMBURSEMENT_PCT VARCHAR,
    CONTRACT_ID           VARCHAR,
    _LOADED_AT            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PATIENTS (
    PATIENT_ID       VARCHAR,
    FIRST_NAME       VARCHAR,
    LAST_NAME        VARCHAR,
    DATE_OF_BIRTH    VARCHAR,
    GENDER           VARCHAR,
    PRIMARY_PAYER_ID VARCHAR,
    MEMBER_ID        VARCHAR,
    ZIP_CODE         VARCHAR,
    _LOADED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PROVIDERS (
    PROVIDER_ID   VARCHAR,
    PROVIDER_NAME VARCHAR,
    NPI           VARCHAR,
    DEPARTMENT    VARCHAR,
    SPECIALTY     VARCHAR,
    _LOADED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ENCOUNTERS (
    ENCOUNTER_ID    VARCHAR,
    PATIENT_ID      VARCHAR,
    PROVIDER_ID     VARCHAR,
    DATE_OF_SERVICE VARCHAR,
    DISCHARGE_DATE  VARCHAR,
    ENCOUNTER_TYPE  VARCHAR,
    DEPARTMENT      VARCHAR,
    _LOADED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CHARGES (
    CHARGE_ID       VARCHAR,
    ENCOUNTER_ID    VARCHAR,
    CPT_CODE        VARCHAR,
    CPT_DESCRIPTION VARCHAR,
    UNITS           VARCHAR,
    CHARGE_AMOUNT   VARCHAR,
    SERVICE_DATE    VARCHAR,
    POST_DATE       VARCHAR,
    ICD10_CODE      VARCHAR,
    _LOADED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS CLAIMS (
    CLAIM_ID            VARCHAR,
    ENCOUNTER_ID        VARCHAR,
    PATIENT_ID          VARCHAR,
    PAYER_ID            VARCHAR,
    DATE_OF_SERVICE     VARCHAR,
    SUBMISSION_DATE     VARCHAR,
    TOTAL_CHARGE_AMOUNT VARCHAR,
    CLAIM_STATUS        VARCHAR,
    IS_CLEAN_CLAIM      VARCHAR,
    SUBMISSION_METHOD   VARCHAR,
    FAIL_REASON         VARCHAR,
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PAYMENTS (
    PAYMENT_ID          VARCHAR,
    CLAIM_ID            VARCHAR,
    PAYER_ID            VARCHAR,
    PAYMENT_AMOUNT      VARCHAR,
    ALLOWED_AMOUNT      VARCHAR,
    PAYMENT_DATE        VARCHAR,
    PAYMENT_METHOD      VARCHAR,
    IS_ACCURATE_PAYMENT VARCHAR,
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS DENIALS (
    DENIAL_ID                 VARCHAR,
    CLAIM_ID                  VARCHAR,
    DENIAL_REASON_CODE        VARCHAR,
    DENIAL_REASON_DESCRIPTION VARCHAR,
    DENIAL_DATE               VARCHAR,
    DENIED_AMOUNT             VARCHAR,
    APPEAL_STATUS             VARCHAR,
    APPEAL_DATE               VARCHAR,
    RECOVERED_AMOUNT          VARCHAR,
    _LOADED_AT                TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS ADJUSTMENTS (
    ADJUSTMENT_ID               VARCHAR,
    CLAIM_ID                    VARCHAR,
    ADJUSTMENT_TYPE_CODE        VARCHAR,
    ADJUSTMENT_TYPE_DESCRIPTION VARCHAR,
    ADJUSTMENT_AMOUNT           VARCHAR,
    ADJUSTMENT_DATE             VARCHAR,
    _LOADED_AT                  TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS OPERATING_COSTS (
    PERIOD             VARCHAR,
    BILLING_STAFF_COST VARCHAR,
    SOFTWARE_COST      VARCHAR,
    OUTSOURCING_COST   VARCHAR,
    SUPPLIES_OVERHEAD  VARCHAR,
    TOTAL_RCM_COST     VARCHAR,
    _LOADED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
