-- ============================================================================
-- METADATA LAYER — AI-queryable semantic and knowledge graph tables
-- ============================================================================
-- Business metadata for Cortex Analyst and the dashboard metadata pages.
-- ============================================================================

USE DATABASE RCM_ANALYTICS;
USE SCHEMA METADATA;

CREATE TABLE IF NOT EXISTS KPI_CATALOG (
    METRIC_NAME   VARCHAR PRIMARY KEY,
    CATEGORY      VARCHAR NOT NULL,
    DEFINITION    VARCHAR,
    FORMULA       VARCHAR,
    DATA_SOURCES  VARCHAR,
    DASHBOARD_TAB VARCHAR,
    BENCHMARK     VARCHAR
);

CREATE TABLE IF NOT EXISTS SEMANTIC_LAYER (
    ID               INTEGER AUTOINCREMENT PRIMARY KEY,
    BUSINESS_CONCEPT VARCHAR NOT NULL,
    KPI_NAME         VARCHAR NOT NULL,
    SILVER_COLUMNS   VARCHAR,
    FORMULA          VARCHAR,
    BUSINESS_RULE    VARCHAR
);

CREATE TABLE IF NOT EXISTS KG_NODES (
    ENTITY_ID     VARCHAR PRIMARY KEY,
    ENTITY_NAME   VARCHAR NOT NULL,
    ENTITY_GROUP  VARCHAR,
    SILVER_TABLE  VARCHAR,
    DESCRIPTION   VARCHAR,
    SOURCE_SYSTEM VARCHAR
);

CREATE TABLE IF NOT EXISTS KG_EDGES (
    ID               INTEGER AUTOINCREMENT PRIMARY KEY,
    PARENT_ENTITY    VARCHAR NOT NULL,
    CHILD_ENTITY     VARCHAR NOT NULL,
    JOIN_COLUMN      VARCHAR,
    CARDINALITY      VARCHAR,
    BUSINESS_MEANING VARCHAR
);

CREATE TABLE IF NOT EXISTS PIPELINE_RUNS (
    DOMAIN         VARCHAR PRIMARY KEY,
    LAST_LOADED_AT TIMESTAMP_NTZ NOT NULL,
    ROW_COUNT      INTEGER,
    SOURCE_FILE    VARCHAR
);

CREATE TABLE IF NOT EXISTS FEATURE_BACKLOG (
    ID                  INTEGER AUTOINCREMENT PRIMARY KEY,
    TITLE               VARCHAR NOT NULL,
    DESCRIPTION         VARCHAR,
    PRIORITY            VARCHAR NOT NULL DEFAULT 'Medium',
    ACCEPTANCE_CRITERIA VARCHAR,
    BENEFITS            VARCHAR,
    STATUS              VARCHAR NOT NULL DEFAULT 'Not Started',
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
