-- ============================================================================
-- Stage → Bronze: Load CSV files from internal stage into Bronze tables
-- ============================================================================
-- Wrapped in a stored procedure so it can be called via:
--   CALL RCM_ANALYTICS.STAGING.SP_LOAD_STAGE_TO_BRONZE();
--
-- Or deployed from Git via:
--   EXECUTE IMMEDIATE FROM @RCM_ANALYTICS.STAGING.RCM_REPO/branches/main/snowflake/etl/load_stage_to_bronze.sql;
--   CALL RCM_ANALYTICS.STAGING.SP_LOAD_STAGE_TO_BRONZE();
--
-- Prerequisites:
--   1. CSV files uploaded to @RCM_ANALYTICS.STAGING.RCM_STAGE
--   2. DDL scripts (01-05) have been run to create tables and stage
-- ============================================================================

USE DATABASE RCM_ANALYTICS;
USE SCHEMA STAGING;

CREATE OR REPLACE PROCEDURE SP_LOAD_STAGE_TO_BRONZE()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    -- Truncate bronze tables before reload (idempotent full refresh)
    TRUNCATE TABLE IF EXISTS BRONZE.PAYERS;
    TRUNCATE TABLE IF EXISTS BRONZE.PATIENTS;
    TRUNCATE TABLE IF EXISTS BRONZE.PROVIDERS;
    TRUNCATE TABLE IF EXISTS BRONZE.ENCOUNTERS;
    TRUNCATE TABLE IF EXISTS BRONZE.CHARGES;
    TRUNCATE TABLE IF EXISTS BRONZE.CLAIMS;
    TRUNCATE TABLE IF EXISTS BRONZE.PAYMENTS;
    TRUNCATE TABLE IF EXISTS BRONZE.DENIALS;
    TRUNCATE TABLE IF EXISTS BRONZE.ADJUSTMENTS;
    TRUNCATE TABLE IF EXISTS BRONZE.OPERATING_COSTS;

    -- Load each CSV into its corresponding Bronze table
    COPY INTO BRONZE.PAYERS (PAYER_ID, PAYER_NAME, PAYER_TYPE, AVG_REIMBURSEMENT_PCT, CONTRACT_ID)
    FROM @STAGING.RCM_STAGE/payers.csv
    FILE_FORMAT = (FORMAT_NAME = 'STAGING.CSV_FORMAT')
    FORCE = TRUE;

    COPY INTO BRONZE.PATIENTS (PATIENT_ID, FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, GENDER, PRIMARY_PAYER_ID, MEMBER_ID, ZIP_CODE)
    FROM @STAGING.RCM_STAGE/patients.csv
    FILE_FORMAT = (FORMAT_NAME = 'STAGING.CSV_FORMAT')
    FORCE = TRUE;

    COPY INTO BRONZE.PROVIDERS (PROVIDER_ID, PROVIDER_NAME, NPI, DEPARTMENT, SPECIALTY)
    FROM @STAGING.RCM_STAGE/providers.csv
    FILE_FORMAT = (FORMAT_NAME = 'STAGING.CSV_FORMAT')
    FORCE = TRUE;

    COPY INTO BRONZE.ENCOUNTERS (ENCOUNTER_ID, PATIENT_ID, PROVIDER_ID, DATE_OF_SERVICE, DISCHARGE_DATE, ENCOUNTER_TYPE, DEPARTMENT)
    FROM @STAGING.RCM_STAGE/encounters.csv
    FILE_FORMAT = (FORMAT_NAME = 'STAGING.CSV_FORMAT')
    FORCE = TRUE;

    COPY INTO BRONZE.CHARGES (CHARGE_ID, ENCOUNTER_ID, CPT_CODE, CPT_DESCRIPTION, UNITS, CHARGE_AMOUNT, SERVICE_DATE, POST_DATE, ICD10_CODE)
    FROM @STAGING.RCM_STAGE/charges.csv
    FILE_FORMAT = (FORMAT_NAME = 'STAGING.CSV_FORMAT')
    FORCE = TRUE;

    COPY INTO BRONZE.CLAIMS (CLAIM_ID, ENCOUNTER_ID, PATIENT_ID, PAYER_ID, DATE_OF_SERVICE, SUBMISSION_DATE, TOTAL_CHARGE_AMOUNT, CLAIM_STATUS, IS_CLEAN_CLAIM, SUBMISSION_METHOD, FAIL_REASON)
    FROM @STAGING.RCM_STAGE/claims.csv
    FILE_FORMAT = (FORMAT_NAME = 'STAGING.CSV_FORMAT')
    FORCE = TRUE;

    COPY INTO BRONZE.PAYMENTS (PAYMENT_ID, CLAIM_ID, PAYER_ID, PAYMENT_AMOUNT, ALLOWED_AMOUNT, PAYMENT_DATE, PAYMENT_METHOD, IS_ACCURATE_PAYMENT)
    FROM @STAGING.RCM_STAGE/payments.csv
    FILE_FORMAT = (FORMAT_NAME = 'STAGING.CSV_FORMAT')
    FORCE = TRUE;

    COPY INTO BRONZE.DENIALS (DENIAL_ID, CLAIM_ID, DENIAL_REASON_CODE, DENIAL_REASON_DESCRIPTION, DENIAL_DATE, DENIED_AMOUNT, APPEAL_STATUS, APPEAL_DATE, RECOVERED_AMOUNT)
    FROM @STAGING.RCM_STAGE/denials.csv
    FILE_FORMAT = (FORMAT_NAME = 'STAGING.CSV_FORMAT')
    FORCE = TRUE;

    COPY INTO BRONZE.ADJUSTMENTS (ADJUSTMENT_ID, CLAIM_ID, ADJUSTMENT_TYPE_CODE, ADJUSTMENT_TYPE_DESCRIPTION, ADJUSTMENT_AMOUNT, ADJUSTMENT_DATE)
    FROM @STAGING.RCM_STAGE/adjustments.csv
    FILE_FORMAT = (FORMAT_NAME = 'STAGING.CSV_FORMAT')
    FORCE = TRUE;

    COPY INTO BRONZE.OPERATING_COSTS (PERIOD, BILLING_STAFF_COST, SOFTWARE_COST, OUTSOURCING_COST, SUPPLIES_OVERHEAD, TOTAL_RCM_COST)
    FROM @STAGING.RCM_STAGE/operating_costs.csv
    FILE_FORMAT = (FORMAT_NAME = 'STAGING.CSV_FORMAT')
    FORCE = TRUE;

    RETURN 'Stage → Bronze load completed successfully (10 tables)';
END;
$$;
